FROM php:7.2-apache
COPY src/ /var/www/html/
EXPOSE 80

#docker build -t my_php72_apache:0.1 .
#shared osx /tools directory with Docker
#docker run -p 80:80 -v /tools/docker/GDrive/DOCKER/Dockerfiles/O/PHP_Apache/src/:/var/ww/html/ 12a552d146e6
